files:
  - source: /core/src/main/resources/*.properties
    ignore:
      - /core/src/main/resources/*_de.properties
      - /core/src/main/resources/*_da.properties
      - /core/src/main/resources/*_es.properties
      - /core/src/main/resources/*_fi.properties
      - /core/src/main/resources/*_fr.properties
      - /core/src/main/resources/*_hr.properties
      - /core/src/main/resources/*_hu.properties
      - /core/src/main/resources/*_it.properties
      - /core/src/main/resources/*_ja.properties
      - /core/src/main/resources/*_ko.properties
      - /core/src/main/resources/*_nl.properties
      - /core/src/main/resources/*_pt.properties
      - /core/src/main/resources/*_ro.properties
      - /core/src/main/resources/*_sk.properties
      - /core/src/main/resources/*_sl.properties
      - /core/src/main/resources/*_sv.properties
      - /core/src/main/resources/*_tr.properties
      - /core/src/main/resources/*_uk.properties
      - /core/src/main/resources/*_ru.properties
      - /core/src/main/resources/ctsms-applicationcontext.properties
      - /core/src/main/resources/*settings.properties
      - /core/src/main/resources/ctsms-dateformats.properties
      - /core/src/main/resources/ctsms-job-mail-sender.properties
      - /core/src/main/resources/ctsms-massmail-mail-sender.properties
      - /core/src/main/resources/ctsms-notification-mail-sender.properties
    translation: /core/src/main/resources/%file_name%_%two_letters_code%.properties
  - source: /web/src/main/resources/org/phoenixctms/ctsms/web/
    ignore:
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_de.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_da.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_es.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_fi.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_fr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_hr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_hu.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_it.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_ja.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_ko.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_nl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_pt.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_ro.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_sk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_sl.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_sv.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_tr.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_uk.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/user/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/trial/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/staff/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/proband/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/massmail/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inventory/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/inputfield/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/course/*_ru.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/settings.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/themes.properties
      - /web/src/main/resources/org/phoenixctms/ctsms/web/windows.properties
    translation: /%original_path%/%file_name%_%two_letters_code%.properties
  - source: /core/src/main/resources/*.vsl
    ignore:
      - /core/src/main/resources/*-de.vsl
      - /core/src/main/resources/*-da.vsl
      - /core/src/main/resources/*-es.vsl
      - /core/src/main/resources/*-fi.vsl
      - /core/src/main/resources/*-fr.vsl
      - /core/src/main/resources/*-hr.vsl
      - /core/src/main/resources/*-hu.vsl
      - /core/src/main/resources/*-it.vsl
      - /core/src/main/resources/*-ja.vsl
      - /core/src/main/resources/*-ko.vsl
      - /core/src/main/resources/*-nl.vsl
      - /core/src/main/resources/*-pt.vsl
      - /core/src/main/resources/*-ro.vsl
      - /core/src/main/resources/*-sk.vsl
      - /core/src/main/resources/*-sl.vsl
      - /core/src/main/resources/*-sv.vsl
      - /core/src/main/resources/*-tr.vsl
      - /core/src/main/resources/*-uk.vsl
      - /core/src/main/resources/*-ru.vsl
    translation: /core/src/main/resources/%file_name%-%two_letters_code%.vsl
